# Generated by Django 4.2.5 on 2023-09-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_inventory_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='Product',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amt',
            field=models.FloatField(editable=False),
        ),
    ]
